import Head from 'next/head';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import Navbar from '../components/Navbar'; // Pastikan path ini benar
import categoriesData from '../data/categories.json'; // Data kategori
import productsData from '../data/products.json'; // Data produk untuk contoh produk unggulan

export default function HomePage({ categories, featuredProducts }) {
  const [email, setEmail] = useState('');
    const [message, setMessage] = useState('');
      const [showPopup, setShowPopup] = useState(false);

        useEffect(() => {
            const timer = setTimeout(() => {
                  setShowPopup(true);
                      }, 30000); // Muncul setelah 30 detik
                          return () => clearTimeout(timer);
                            }, []);

                              const handleSubscribe = async (e) => {
                                  e.preventDefault();
                                      setMessage('Processing...');
                                          try {
                                                const res = await fetch('/api/subscribe', {
                                                        method: 'POST',
                                                                headers: {
                                                                          'Content-Type': 'application/json',
                                                                                  },
                                                                                          body: JSON.stringify({ email }),
                                                                                                });
                                                                                                      const data = await res.json();
                                                                                                            if (res.ok) {
                                                                                                                    setMessage('Terima kasih! Email Anda sudah terdaftar.');
                                                                                                                            setEmail('');
                                                                                                                                    setShowPopup(false); // Sembunyikan popup setelah berhasil subscribe
                                                                                                                                          } else {
                                                                                                                                                  setMessage(data.error || 'Gagal mendaftar.');
                                                                                                                                                        }
                                                                                                                                                            } catch (error) {
                                                                                                                                                                  setMessage('Terjadi kesalahan. Silakan coba lagi.');
                                                                                                                                                                      }
                                                                                                                                                                        };

                                                                                                                                                                          return (
                                                                                                                                                                              <div className="container">
                                                                                                                                                                                    <Head>
                                                                                                                                                                                            <title>Selamat Datang di Situs Afiliasi Kami</title>
                                                                                                                                                                                                    <meta name="description" content="Temukan ulasan produk terbaik dan penawaran afiliasi." />
                                                                                                                                                                                                            <link rel="icon" href="/favicon.ico" />
                                                                                                                                                                                                                  </Head>
                                                                                                                                                                                                                        <Navbar categories={categories} />

                                                                                                                                                                                                                              <main className="main">
                                                                                                                                                                                                                                      <section className="hero">
                                                                                                                                                                                                                                                <h1>Temukan Produk Terbaik Pilihan Kami</h1>
                                                                                                                                                                                                                                                          <p>Ulasan mendalam dan rekomendasi terpercaya untuk membantu Anda membuat keputusan pembelian yang tepat.</p>
                                                                                                                                                                                                                                                                  </section>

                                                                                                                                                                                                                                                                          <section className="featured-categories">
                                                                                                                                                                                                                                                                                    <h2>Kategori Unggulan</h2>
                                                                                                                                                                                                                                                                                              <div className="categories-grid">
                                                                                                                                                                                                                                                                                                          {categories.slice(0, 4).map(category => (
                                                                                                                                                                                                                                                                                                                        <Link key={category.id} href={`/categories/${category.id}`} legacyBehavior>
                                                                                                                                                                                                                                                                                                                                        <a className="category-card">
                                                                                                                                                                                                                                                                                                                                                          <h3>{category.name}</h3>
                                                                                                                                                                                                                                                                                                                                                                            <p>{category.description.substring(0, 60)}...</p>
                                                                                                                                                                                                                                                                                                                                                                                            </a>
                                                                                                                                                                                                                                                                                                                                                                                                          </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                      ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                        </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                <section className="featured-products">
                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h2>Produk Terbaru / Paling Populer</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="products-grid">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {featuredProducts.slice(0, 3).map(product => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div key={product.id} className="product-card-simple">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <img src={product.imageUrl || '/placeholder-image.png'} alt={product.name} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <h3>{product.name}</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p>Harga: Rp {product.price.toLocaleString()}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Link href={`/products/${product.id}`} legacyBehavior>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <a className="btn-detail">Lihat Detail</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {showPopup && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="email-popup">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="popup-content">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button className="close-popup" onClick={() => setShowPopup(false)}>&times;</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <h3>Dapatkan Update Terbaru!</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p>Daftarkan email Anda untuk mendapatkan panduan gratis "10 Alat AI Terbaik untuk Otomatisasi Bisnis Online" dan info produk terbaru.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <form onSubmit={handleSubscribe}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <input 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            type="email" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              placeholder="Masukkan email Anda" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                value={email} 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onChange={(e) => setEmail(e.target.value)} 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    required 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button type="submit">Daftar Sekarang</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {message && <p className="popup-message">{message}</p>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <section className="community-cta">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h2>Bergabung dengan Komunitas Kami!</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p>Dapatkan tips eksklusif, diskusi, dan dukungan dari sesama anggota.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <a href="https://t.me/nama_grup_telegram_anda" target="_blank" rel="noopener noreferrer" className="btn-community telegram">Gabung Telegram</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <a href="https://facebook.com/groups/nama_grup_facebook_anda" target="_blank" rel="noopener noreferrer" className="btn-community facebook">Gabung Facebook Group</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </main>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <footer className="footer">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p>&copy; {new Date() .getFullYear()} Situs Multi-Afiliasi Anda. Dibuat dengan ❤️</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </footer>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              export async function getStaticProps() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Di lingkungan nyata, Anda mungkin fetch dari API atau database
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // Untuk sekarang, kita impor langsung dari file JSON
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        props: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              categories: categoriesData,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    featuredProducts: productsData, // Mengambil semua produk sebagai contoh
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          